// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtNJFu8oWsssq-UVy199elPTFMpy-ciLI',
    appId: '1:568433684146:web:597cd6b32c20a7fa56e3ab',
    messagingSenderId: '568433684146',
    projectId: 'ezapply-838dc',
    authDomain: 'ezapply-838dc.firebaseapp.com',
    storageBucket: 'ezapply-838dc.appspot.com',
    measurementId: 'G-RL7FKBLSJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGv8zP5BRdDt7jHHlPj5aIccpuZxgHIkM',
    appId: '1:568433684146:android:c8fb7692c4dad07656e3ab',
    messagingSenderId: '568433684146',
    projectId: 'ezapply-838dc',
    storageBucket: 'ezapply-838dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmOetkasGuIpyfHu-CmIMpx9FLUh70pKA',
    appId: '1:568433684146:ios:7c5cbfc0a917b48456e3ab',
    messagingSenderId: '568433684146',
    projectId: 'ezapply-838dc',
    storageBucket: 'ezapply-838dc.appspot.com',
    iosClientId: '568433684146-g81i69irrna3jlm88hn7rbtlj2ib8sf0.apps.googleusercontent.com',
    iosBundleId: 'com.example.ezapplyadmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmOetkasGuIpyfHu-CmIMpx9FLUh70pKA',
    appId: '1:568433684146:ios:7c5cbfc0a917b48456e3ab',
    messagingSenderId: '568433684146',
    projectId: 'ezapply-838dc',
    storageBucket: 'ezapply-838dc.appspot.com',
    iosClientId: '568433684146-g81i69irrna3jlm88hn7rbtlj2ib8sf0.apps.googleusercontent.com',
    iosBundleId: 'com.example.ezapplyadmin',
  );
}
